### ISSUE TITLE
fix: migrate to Talos `UserVolumeConfig`

### ISSUE THREAD

**Issue by smauermann** [smauermann/homelab#503]
Replace `machine.disks` with the following for all nodes:

```yaml
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: storage
provisioning:
  diskSelector:
    match: disk.symlinks.exists(link, link.matches("TBD"))
  minSize: 1TB
```
Remove `machine.kubelet.extraMounts`.

Remove disks in each node config.

Ref: https://www.talos.dev/v1.10/reference/configuration/block/uservolumeconfig/
